<ItemLabel@Label>:
    font_size: "25sp"

<Contenedor_01>:

    orientation: "vertical"
    ItemLabel:
        text: "Welcome to Heds or Tails"

    BoxLayout:
        orientation: "horizontal"
        Button:
            text:"Teads"
            on_release: root.choice("heads")
        Button:
            text:"Tails"
            on_release: root.choice("tails")
        Label:
            text:"Hola"
    Label:
        id: result
        text: ""
        font_size: 40
